export const KEYBOARD_SHORTCUTS: Array<{ category: string; key: string; description: string }> = [
  { category: "navigation", key: "j / ↓", description: "Scroll down" },
  { category: "navigation", key: "k / ↑", description: "Scroll up" },
  { category: "navigation", key: "space / PgDn", description: "Page down / toggle picker selection" },
  { category: "navigation", key: "b / PgUp", description: "Page up" },
  { category: "navigation", key: "Home", description: "Jump to chapter start" },
  { category: "navigation", key: "End", description: "Jump to chapter end" },
  { category: "navigation", key: "← / →", description: "Previous / next chapter" },
  { category: "navigation", key: "T", description: "Open table of contents" },
  { category: "navigation", key: "B", description: "Open bookmarks" },
  { category: "navigation", key: "[ / ]", description: "Back / forward in navigation history" },
  { category: "navigation", key: "wheel", description: "Scroll the page" },
  { category: "navigation", key: "g", description: "Jump to top" },
  { category: "navigation", key: "G", description: "Jump to bottom" },
  { category: "commands", key: "n / N", description: "Next / previous search match (after /search)" },
  { category: "commands", key: "/", description: "Focus command bar" },
  { category: "commands", key: "Enter", description: "Run command / confirm picker" },
  { category: "commands", key: "Esc", description: "Close overlay or blur command input" },
  { category: "commands", key: "d", description: "Delete selected bookmark (inside bookmark overlay)" },
  { category: "commands", key: "?", description: "Open keyboard shortcuts" },
  { category: "view", key: "m", description: "Cycle render mode (plain → typescript → python → rust)" },
  { category: "view", key: "c", description: "Open colorscheme picker" },
  { category: "view", key: "p", description: "Cycle progress bar visibility" },
  { category: "view", key: "Tab", description: "Autocomplete or cycle command suggestions" },
  { category: "view", key: "q", description: "Quit the reader" }
];
