export const KEYBOARD_SHORTCUTS: Array<{ category: string; key: string; description: string }> = [
  { category: "navigation", key: "j / ↑", description: "Scroll up" },
  { category: "navigation", key: "k / ↓", description: "Scroll down" },
  { category: "navigation", key: "space / PgDn", description: "Page down / toggle picker selection" },
  { category: "navigation", key: "b / PgUp", description: "Page up" },
  { category: "navigation", key: "Home", description: "Jump to chapter start" },
  { category: "navigation", key: "End", description: "Jump to chapter end" },
  { category: "navigation", key: "← / →", description: "Previous / next chapter" },
  { category: "navigation", key: "Shift+T", description: "Open table of contents" },
  { category: "navigation", key: "Shift+B", description: "Open bookmarks" },
  { category: "navigation", key: "[ / ]", description: "Back / forward in navigation history" },
  { category: "navigation", key: "wheel", description: "Scroll the page" },
  { category: "navigation", key: "g", description: "Jump to top" },
  { category: "navigation", key: "Shift+G", description: "Jump to bottom" },
  { category: "commands", key: "n / Shift+N", description: "Next / previous search match (after /search)" },
  { category: "commands", key: "/", description: "Focus command bar" },
  { category: "commands", key: "Enter", description: "Run command / confirm picker" },
  { category: "commands", key: "Esc", description: "Close overlay or blur command input" },
  { category: "commands", key: "d", description: "Delete selected bookmark (inside bookmark overlay)" },
  { category: "commands", key: "s (books)", description: "Cycle sort key in book library" },
  { category: "commands", key: "r (books)", description: "Reverse sort direction in book library" },
  { category: "commands", key: "? / Ctrl+. / Ctrl+X", description: "Open keyboard shortcuts" },
  { category: "view", key: "m", description: "Cycle render mode (plain → typescript → python → rust)" },
  { category: "view", key: "f", description: "Toggle focus mode (single block centered)" },
  { category: "view", key: "c", description: "Open colorscheme picker" },
  { category: "view", key: "Shift+C", description: "Open theme picker" },
  { category: "view", key: "Shift+S", description: "Open tabbed reader settings with live preview" },
  { category: "view", key: "p", description: "Cycle progress display (time left / % bars / hidden)" },
  { category: "view", key: "Tab", description: "Autocomplete or cycle command suggestions" },
  { category: "view", key: "q", description: "Quit the reader" }
];
